line-length = 120
target-version = "py38"

[lint]
extend-select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # Pyflakes
    "I",  # isort
    "D",  # pydocstyle
    "C90",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "Q",  # flake8-quotes
    "S",  # flake8-bandit
    "ASYNC", # flake8-async
    "ANN", # flake8-annotations
    "C",
    "BLE",
    "ERA",
    "ICN",
    "INP",
    "ISC",
    "NPY",
    "PGH",
    "PIE",
    "RET",
    "RSE",
    "RUF",
    "SIM",
    "T20",
    "TC",
    "TID",
    "YTT",
]
ignore = [
    "PGH003", "PGH004", # use specific rule code with noqa; works bad with JetBrains IDE Warnings
    "ANN401", # t.Any in **kwargs
    "ANN002", # Missing type annotation for `*args`
    "ANN003", # Missing type annotation for `**kwargs
    "D203", "D413", # we are not using too many blank lines
    "D213", # we are using the first line for summary
    "D406", "D407", # we are using google style docstring
    "S101", # allow asserting; we are using it for type checks
    "ISC001", # conflicts with format
    "RUF001", "RUF002", "RUF003", # cyrillic
]

[lint.per-file-ignores]
"yandex_music/*.py" = [
    "D105", "D104", "D100", "D107", "D103", "D415", # missing docstring
    "D400", # first line should end with a period. TODO(MarshalX): We are using strange docsting style for methods-shortcuts
]
"yandex_music/__init__.py" = ["I001"] # Import sort
"yandex_music/client*.py" = ["T201"] # print
"yandex_music/_client/*.py" = ["T201"] # print (generated)
"yandex_music/_client_async/*.py" = ["T201"] # print
"tests/*.py" = ["S101", "S105", "S106", "ANN", "D", "RUF012"]
"tests/__init__.py" = ["F401"] # Unused import
"test.py" = ["S101", "ERA001", "T201", "E501", "F401", "F841"]
"docs/source/conf.py" = ["INP001"]
"docs/generate_client_docs.py" = ["INP001", "T201"]
"examples/*.py" = ["T201", "S311", "ERA001", "INP001", "S106", "BLE001", "S603", "ANN", "D"]

[lint.flake8-quotes]
docstring-quotes = "double"
multiline-quotes = "double"
inline-quotes = "single"

[format]
quote-style = "single"
