from .test_about_artist import TestArtistAbout
from .test_account import TestAccount
from .test_ad_params import TestAdParams
from .test_album import TestAlbum
from .test_album_action_button import TestAlbumActionButton
from .test_album_event import TestAlbumEvent
from .test_album_similar_entities import TestAlbumSimilarEntities
from .test_album_trailer import TestAlbumTrailer
from .test_alert import TestAlert
from .test_alert_button import TestAlertButton
from .test_artist import TestArtist
from .test_artist_clip_data import TestArtistClipData
from .test_artist_clip_item import TestArtistClipItem
from .test_artist_clips import TestArtistClips
from .test_artist_concerts import TestArtistConcerts
from .test_artist_donation_data import TestArtistDonationData
from .test_artist_donation_goal import TestArtistDonationGoal
from .test_artist_donation_item import TestArtistDonationItem
from .test_artist_donations import TestArtistDonations
from .test_artist_event import TestArtistEvent
from .test_artist_info import TestArtistInfo
from .test_artist_link import TestArtistLink
from .test_artist_links import TestArtistLinks
from .test_artist_similar import TestArtistSimilar
from .test_artist_skeleton import TestArtistSkeleton
from .test_artist_trailer import TestArtistTrailer
from .test_artist_trailer_status import TestArtistTrailerStatus
from .test_auto_renewable import TestAutoRenewable
from .test_best import TestBest
from .test_block import TestBlock
from .test_block_entity import TestBlockEntity
from .test_brand import TestBrand
from .test_case_forms import TestCaseForms
from .test_chart import TestChart
from .test_chart_info import TestChartInfo
from .test_chart_info_menu import TestChartInfoMenu
from .test_chart_info_menu_item import TestChartInfoMenuItem
from .test_clip import TestClip
from .test_clips_will_like import TestClipsWillLike
from .test_concert import TestConcert
from .test_concert_cashback import TestConcertCashback
from .test_concert_description import TestConcertDescription
from .test_concert_event_info import TestConcertEventInfo
from .test_concert_feed import TestConcertFeed
from .test_concert_feed_item import TestConcertFeedItem
from .test_concert_feed_item_data import TestConcertFeedItemData
from .test_concert_info import TestConcertInfo
from .test_concert_location import TestConcertLocation
from .test_concert_locations import TestConcertLocations
from .test_concert_min_price import TestConcertMinPrice
from .test_concert_skeleton import TestConcertSkeleton
from .test_concert_tab_config import TestConcertTabConfig
from .test_concert_tab_config_data import TestConcertTabConfigData
from .test_concert_tab_range import TestConcertTabRange
from .test_content_restrictions import TestContentRestrictions
from .test_contest import TestContest
from .test_context import TestContext
from .test_counts import TestCounts
from .test_cover import TestCover
from .test_cover_derived_colors import TestCoverDerivedColors
from .test_credit import TestCredit
from .test_credits import TestCredits
from .test_custom_wave import TestCustomWave
from .test_day import TestDay
from .test_deactivation import TestDeactivation
from .test_deprecation import TestDeprecation
from .test_description import TestDescription
from .test_disclaimer import TestDisclaimer
from .test_discrete_scale import TestDiscreteScale
from .test_enum import TestEnum
from .test_event import TestEvent
from .test_experiment_detail import TestExperimentDetail
from .test_experiment_detail_value import TestExperimentDetailValue
from .test_experiments_details import TestExperimentsDetails
from .test_fade import TestFade
from .test_foreign_agent import TestForeignAgent
from .test_generated_playlist import TestGeneratedPlaylist
from .test_genre import TestGenre
from .test_icon import TestIcon
from .test_id import TestId
from .test_images import TestImages
from .test_invocation_info import TestInvocationInfo
from .test_label import TestLabel
from .test_label_albums import TestLabelAlbums
from .test_label_artists import TestLabelArtists
from .test_licence_text_part import TestLicenceTextPart
from .test_link import TestLink
from .test_lyrics import TestLyrics
from .test_lyrics_info import TestLyricsInfo
from .test_lyrics_major import TestLyricsMajor
from .test_made_for import TestMadeFor
from .test_major import TestMajor
from .test_meta_data import TestMetaData
from .test_metatag import TestMetatag
from .test_metatag_albums import TestMetatagAlbums
from .test_metatag_artist_entry import TestMetatagArtistEntry
from .test_metatag_artists import TestMetatagArtists
from .test_metatag_leaf import TestMetatagLeaf
from .test_metatag_playlists import TestMetatagPlaylists
from .test_metatag_sort_by_value import TestMetatagSortByValue
from .test_metatag_title import TestMetatagTitle
from .test_metatag_tree import TestMetatagTree
from .test_metatags import TestMetatags
from .test_mix_link import TestMixLink
from .test_music_history import TestMusicHistory
from .test_music_history_context_full_model import TestMusicHistoryContextFullModel
from .test_music_history_group import TestMusicHistoryGroup
from .test_music_history_item import TestMusicHistoryItem
from .test_music_history_item_data import TestMusicHistoryItemData
from .test_music_history_item_id import TestMusicHistoryItemId
from .test_music_history_items import TestMusicHistoryItems
from .test_music_history_tab import TestMusicHistoryTab
from .test_non_auto_renewable import TestNonAutoRenewable
from .test_normalization import TestNormalization
from .test_open_graph_data import TestOpenGraphData
from .test_operator import TestOperator
from .test_pager import TestPager
from .test_passport_phone import TestPassportPhone
from .test_permissions import TestPermissions
from .test_personal_playlists_data import TestPersonalPlaylistsData
from .test_pin import TestPin
from .test_pin_data import TestPinData
from .test_pins_list import TestPinsList
from .test_play_context import TestPlayContext
from .test_play_contexts_data import TestPlayContextsData
from .test_play_counter import TestPlayCounter
from .test_playlist import TestPlaylist
from .test_playlist_absence import TestPlaylistAbsence
from .test_playlist_availability import TestPlaylistAvailability
from .test_playlist_id import TestPlaylistId
from .test_playlist_similar_entities import TestPlaylistSimilarEntities
from .test_playlist_trailer import TestPlaylistTrailer
from .test_playlists_list import TestPlaylistsList
from .test_plus import TestPlus
from .test_poetry_lover_match import TestPoetryLoverMatch
from .test_presaves import TestPresaves
from .test_price import TestPrice
from .test_product import TestProduct
from .test_promotion import TestPromotion
from .test_queue_item import TestQueueItem
from .test_r128 import TestR128
from .test_ratings import TestRatings
from .test_renewable_remainder import TestRenewableRemainder
from .test_restrictions import TestRestrictions
from .test_rotor_settings import TestRotorSettings
from .test_search_result import TestSearchResult
from .test_sequence import TestSequence
from .test_settings import TestSettings
from .test_shot import TestShot
from .test_shot_data import TestShotData
from .test_shot_type import TestShotType
from .test_similar_entity_data import TestSimilarEntityData
from .test_similar_entity_item import TestSimilarEntityItem
from .test_skeleton_block import TestSkeletonBlock
from .test_skeleton_block_data import TestSkeletonBlockData
from .test_skeleton_source import TestSkeletonSource
from .test_skeleton_tab import TestSkeletonTab
from .test_skeleton_view_all_action import TestSkeletonViewAllAction
from .test_smart_preview_params import TestSmartPreviewParams
from .test_station import TestStation
from .test_station_data import TestStationData
from .test_station_result import TestStationResult
from .test_stats import TestStats
from .test_status import TestStatus
from .test_subscription import TestSubscription
from .test_suggestions import TestSuggestions
from .test_tag import TestTag
from .test_title import TestTitle
from .test_track import TestTrack
from .test_track_full_info import TestTrackFullInfo
from .test_track_id import TestTrackId
from .test_track_lyrics import TestTrackLyrics
from .test_track_position import TestTrackPosition
from .test_track_short import TestTrackShort
from .test_track_short_old import TestTrackShortOld
from .test_track_trailer import TestTrackTrailer
from .test_track_with_ads import TestTrackWithAds
from .test_trailer_info import TestTrailerInfo
from .test_user import TestUser
from .test_value import TestValue
from .test_video import TestVideo
from .test_video_supplement import TestVideoSupplement
from .test_vinyl import TestVinyl
from .test_wave import TestWave
from .test_wave_agent import TestWaveAgent
from .test_wave_agent_entity import TestWaveAgentEntity
