name: Codegen check

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  codegen_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v6

      - name: Setup uv.
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies.
        run: uv sync --locked --all-extras --no-default-groups --group codegen --group docs

      - name: Run codegen.
        env:
          UV_NO_SYNC: "1"
        run: |
          make gen
          uv run make -C docs gen

      - name: Check working directory is clean.
        run: git diff --exit-code
