name: Codecov

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v6

      - name: Setup uv.
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies.
        run: uv sync --locked --all-extras --no-default-groups --group test

      - name: Test with pytest and generate coverage.
        run: uv run --no-sync pytest -v --cov=yandex_music --cov-report=xml

      - name: Submit coverage.
        if: github.ref == 'refs/heads/main' && github.repository == 'MarshalX/yandex-music-api'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: github
          name: GHA
