name: Codegen check

on: [ pull_request ]

permissions:
  contents: read

jobs:
  codegen_check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies.
        run: pip install -r requirements-dev.txt

      - name: Run codegen.
        run: |
          make gen
          cd docs
          make gen

      - name: Check working directory is clean.
        run: git diff --exit-code
