name: Linter and code style check

on: [ pull_request ]

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4

      - name: Setup Python.
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Run linter check.
        uses: chartboost/ruff-action@v1
        with:
          version: 0.1.6

      - name: Run code style check.
        uses: chartboost/ruff-action@v1
        with:
          version: 0.1.6
          args: format --check
