name: Linter and code style check

on:
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v6

      - name: Setup uv.
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies.
        run: uv sync --locked --only-group lint

      - name: Run linter check.
        run: uv run --no-sync ruff check --output-format=github .

      - name: Run code style check.
        run: uv run --no-sync ruff format --check .
